version: '2'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
    postgres:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=prodigy
            - POSTGRES_PASSWORD=prodigy
        ports:
            - 5432:5432
    app:
        build: 
            context: ./docker
            dockerfile: app.dockerfile
        environment:
            - DATA_DIR=/data
            - DB_HOST=postgres
            - DB_USER=prodigy
            - DB_PASS=prodigy
            - BASE_URL=http://192.168.99.100
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        ports:
            - 80:8080
        volumes:
            - ./src:/app
            - ./data:/data
        depends_on:
            - redis
            - postgres
#            - worker
        command: python3 main.py
#        restart: always
#    worker:
#        build:
#            context: ./docker
#            dockerfile: app.dockerfile
#        environment:
#            - LISTEN_PORT=6000
#            - DATA_DIR=/data
#            - DB_HOST=postgres
#            - DB_USER=prodigy
#            - DB_PASS=prodigy
#            - CELERY_BROKER=redis://redis:6379/0
#            - CELERY_BACKEND=redis://redis:6379/0
#        volumes:
#            - ./src:/app
#            - ./data:/data
#        depends_on:
#            - redis
#            - postgres
#        command: celery -A tasks worker -l warning -Q prodigy --concurrency=1
#        restart: always
#    jupyter:
#        build:
#            context: ./docker
#            dockerfile: jupyter.dockerfile
#        volumes:
#            - ./data:/data
#        ports:
#            - 8888:8888
#        command: start.sh jupyter lab
#        restart: always